### ISSUE TITLE
Deploy production HTTPS bouncer, collector and web_connectivity test helper

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-sysadmin#61]
This ticket is about updating the canonical bouncer, collector and web_connectivity test helper to support.

I believe the bouncer YAML configuration file should look something like this:

```
collector:
  httpo://ihiderha53f36lsd.onion:
    collector-alternate:
    - {address: 'https://a.collector.ooni.io', type: 'https'}
    test-helper: {dns: '213.138.109.232:57004', ssl: 'https://213.138.109.232', tcp-echo: '213.138.109.232', traceroute: '213.138.109.232', web-connectivity: 'httpo://7jne2rpg5lsaqs6b.onion'}
    test-helper-alternate:
        web-connectivity:
        - {address: 'https://web-connectivity.ooni.io', type: 'https'}
```

Let me know if you need some A records to be setup for this.
